# Generated by Django 4.1 on 2022-11-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0002_rename_mytodo_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='username',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
