# Generated by Django 4.1 on 2022-11-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0003_todo_password_todo_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='todo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='username',
        ),
    ]
